# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

env:
  global:
    # OPENSHIFT_LOGIN
    - secure: "FAzAACSaaHX05q/S33IUH7sKpawdxeBbCloFK9k6M1OqBc1rHT5rrflj2sZGGsa8Re70OGaowmmvGrGYhaV8GhWi9bErQbvDaUbajkzTYpXzjk1K5HseFhjyPMpdE1sJdnLUm3lOWZ1bxrmHkU2TLce85g22w1QgbXbgWJ8upTMofzNbjkAiMWrZaBqcp37QxvABWTfPISVhOt4bfud7yeNdjGt/u+L2ZekT9qc3ZEXLIJEAJ+CyxxbmD00aUIjLSYLIDQ+PE3cJNsmFqFiVDAGT0ruWzTPCT9uUgN4poCNh5JSVyDZLOrKetSYzQEC2sRIprfMUk83ffDd7h4toJXkAKMqjwcf0Al7Doos8MnoG0jctumJbxETsFaKtfkrTFzcdLOQUm2+EW/E3bcgV1psFRkMJbmc3V7L1QIc7aePrIIrvL6x1qJsl6zGXkUEvRHXCXpBKQoziqWFvNjtOiKxzT86z4n+SDJWq5VxtZHumsSUBMvXq89Xj0KAJG5JUOhHB+rjBP5B6oFkiYSIsLTqFEYVn9clZDeTlYx283c+y9vGLfxePeqvo5UY7pEqx//3UNXEYtRr4NwZCBGKWk7zVmJKELal6l9U0RHWO6O1j9H60Smt3p3Vfrkl/SCmdOrszlucZ8T8WY8+Dnqdf1Z31uS+NJ2bQzgvkjooIsw4="
    # OPENSHIFT_PASSWORD
    - secure: "oDT5KFJYCbStLNaL9L4oOUtVpinoXxXpabr+XvfGjA11SdUjq5thorA0PHGy/+Kpo+KC2HA4+sFxq8GByK9EUoyqfOYkUi4qs4U5fdiVK4nCTxX/lkc22C0r0fAz6ZHeFVJS8lLx3q2UULfoTP0b2lXOpO+ABKg++OKyVqNCpUoIp9U9fcg/BWRhOlWshDUt2Jj0ZRvl2gEJQaWWjQcx15gqeygSFaB1w/sI+LFmh/DS6XOYnhEhi6im+zo1abUi4EAw7z8cx0FVwqfuoOQ9RDZaG8UnGBdQspRc9/yKmQ+rmlYuP0ghJXjH1MdWjT5QK0i5zFqCckfCV2YUFWK0huYL8U2ElLwLzaBCT9rYC0LOTCHUX1AjONtsuC4LColze2AIs1UzmAAI03EX+OkGhs39ve0VqouzC/pJpqv0aHUNn2f8aQNQ/1hBMilT+YFtR3TNiXzGE+Rp5kY6xddhk+1K1GYD/IE5ynTwABzN1204X/FLkJKUH5xxHprvRd9ApS1YuHM8X2MwbbNeb9nuYZumEW7hAW6MHWnvsLJlTM28nI6ey4V6Ckao11JwWTif32rqzXhrIiQ2+aQ1rqnv8Gpcv+6u6i+GLFBfj57wUWR6Z4T4vUIVC2j1LTco9VU8GLmGZxXM08EduooHPyrKzaRUJng+iA9v3Fhv6hvMTTc="
    # DB_URL TODO
    - secure: Tn35+8uWWPG/py32akIiBdeDgRWqTMKF4bBB9UVyEGDD/F71u29jr8jO8098zOb1lMV9fzIGoUroL0EcBV1igMawFuumGMA9+7KZH/JH3obq12VhRorkP/yRUgLEOREtBFRdTLFRN5lnwMGDVjoCJTyiEw2GlN0cEV9ZzIxVj+fPtwpV86WL/zXPmayzFRIh9R577N/V5oGy2XGYQRsnWg1Nv7TU48o12g4gic7iExZLTMVDps59TrEloCFwBntHZr+ACDsW9HXX+sCxza7XR1IpeBfgc+prQL2cM3/d+DEEzbSLTm22Zjq4r/hHqs7kaz+UOeL6CWFDqzXFshDeNHKXKLBdTHsMYmWDEOiZUWHAvqrnue3nyXCQO/AqSS/cVLl8LTnTIJZvjBLHIYsbM/0QtkOWKi2o5cWpBuQAJ5j4EYQiR9q2ww+9RBpss6HkSHuLNdotQdIQMb2O22BpLGXDrA2v81GtTPLhQoJ52BxeL2FEvq3ru0lcM//tNmjPYgHRQ9LcvnszRrca6c3V5mwLDTX8O4tB6oyuybFg3yh21W5OCUR0PhTWjfbpSZOMZNCMes/HGlw0W8KyEjXP4q86hFP4LF4qES/rZUfhT8XfU8zYtOsfjWcqVkWxogZd2abj7CYMkJn385PpGrRjJuX2b88BkRS4KAdmaQv1wzY=
    # DB_USERNAME TODO
    - secure: IZCFAQ0zJUA6jlTqHmbY52NPbbddkNeTPNKQZXvzcmgprSAq1Y9ZMdlyNpPGYigG+PN4Tkw2ZaklyzR43z3736euTdovVVqeN7HjGjQJd044OhuL9uslCIUBQf0WH7bNtHANgN9cJ7itrXG8tpY9Kw7gn46ZT2CwBv9cdOGOMhQd6yN1q6gLIzkgb/yD+5f27XsLrTnBExwDW2/pseMXhkrpkSg54dv8IfyRGQJK9vVZxCjRzb+l918TnQtsuyGphjBfd51YUO1j3QPmwy2ZRvyse9ghfcQ3aTZjCvoHS3XedjQKbC3hnHCf2Qqr22D0lbv2+oyqxWe5M0EGXpe0Go1FKxLaKIIAB0iboe6Hkehsw2USvu+gkS1ISIh5qt7rYg4fkDncJk8/ihG8M/3+3w6Q6vdmLXEC6GmKzJsZGfHrGtp+mTKWe02zzrpSTYarcN7Y+s5g+v9y8LGPDpTEVP0mfZBltxBEophrHgOqgFrGSZbg4YnALrBMLUmFXIg64PkGn0rGGdyF6RoC0dE2JbbmIDJsCJgviTMRe5oPXoQ1961Vz7urqcx4yzK5T3IipFRv0+qTnpuZdjgfxMOR4ApgkldSis7epuaKvsTNeEDWwMfr4FIYg41Ua3oasKdubK7NUgGFQKhajxPQUbePlXLfz9CkW96/kvXe3+Q8mes=
    # DB_PASSWORD TODO
    - secure: CHZkRXrerJkRZYZPngo+H+ydP1u85Jd7DtsnPtaR80ieaoWbzq8D/VCRZ/zzUfb9TyQTqmnlGMg5C8zYrxDZgiKc5axWEz8optxV3neooJYQ7Lf00qE1GPGRppkPycoYY6bMSjiJgvOmAnvKkvcOb2hUDHDCS4Mp8e2Ap8NIAdLCvE9T0Uqs19i4G+fODZC01lG8EI9TKnbxp6AkHlVcuJP0cjBoHQ/fiDorhxK8phND+YZCKide9AC0nNKv1lj0p8GKpcyZ9OFMowGpTugv20nHNKPd6wNOXIdGV9+aFVxhb23P3JZ+ebgOJywGDcv39h4iUUI0ioFYkEAZBf+GnO6BJ9aP3LCDuOv9aIRrtUIYwmEvJbHYL4N1lk1wUJOCedY2cO6pN9aofBq125gkkMQD2VR/bDveDwfqeyJThI5UZ6tozNatUeAXFUDvAgHAwtTBcn8xwCRVP1d4zQtFmmPxzr9aoJ5aJOYu9xjowKXqmgc5ixtlxtuSq4VJ2D9he4NQxMlTmROS1Wjf8z28O7PUAAFCfIlXllAUe63AzgThV0p8gL0H4KXoVDpMslcR0jyvjWa4MUeQKXXmNsdg2RNM1CYgisfc7V8qtvFcKRm0dI6mgPR+9ng1heKB/jISsIGD5fzv+YUtrnsC36s0nWZKttLNFZfM3fqVM2Z89dw=

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - oraclejdk7

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - openssl aes-256-cbc -K $encrypted_3e5e4c02969c_key -iv $encrypted_3e5e4c02969c_iv -in id_rsa_openshift_travis.enc -out id_rsa_openshift_travis -d
  - mv id_rsa_openshift_travis ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - npm install -g bower-installer

install:
  - mvn clean install
    -DskipTests=true
    -Dmaven.javadoc.skip=true
    -Dbase.database.driver.classname=com.mysql.jdbc.Driver
    -Dbase.database.url=$DB_URL
    -Dbase.database.username=$DB_USERNAME
    -Dbase.database.password=$DB_PASSWORD
    -Popenshift -B -V

after_success:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then echo "No deployment because branch is not master."; exit 0; fi
  - cp webapps/ROOT.war binary/dependencies/jbossews/webapps/ROOT.war
  - cp -r .openshift/* binary/repo/.openshift
  - cd binary
  - tar -czvf ../webapps/binary.tar.gz ./
  - cd ..
  - gem install rhc
  - rhc deploy -a base webapps/binary.tar.gz --no-force-clean-build -l $OPENSHIFT_LOGIN -p $OPENSHIFT_PASSWORD
